server.port: 8082
message: test is taking.

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/india?autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: india
    password: india
