server.port: 8084
message: uat is taking.

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/europe?autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: europe
    password: europe
